### ISSUE TITLE
DB optimalizace

### ISSUE THREAD

**Issue by foton** [sinfin/auctify#11]
- counter cache pro `auction.bids_count`
- `winner` nebo `winning_bid` relaci pro `sale/auction`, aby slo eager loadovat do vypisu. To stavajici reseni bude pro vypis 150 sales pomale (n+1)

**Comment by foton** [comment]
Kde se bude těch 150 sales vypisovat najednou? v konzoli.

**Comment by foton** [comment]
A zajímá tě to až po skončení aukce nebo i v průběhu?

**Comment by foton** [comment]
`Winner` bude lepší (bid asi není tak podstatný, cenu máme u aukce) . S `inludes` by to mělo být na dva dotazy.
U ukončené aukce lze použít asociaci `buyer` ( pokud je nastaveno autouzavírání aukcí).
`Auctify::Sale::Auction.includes(:buyer)`

**Comment by mreq** [comment]
@foton NA figme se dozvis odpovedi https://www.figma.com/file/nsF3MJkKTvw7xujDtyA48v/Folio---Console?node-id=790%3A4886

> Kde se bude těch 150 sales vypisovat najednou? v konzoli.

Na hlavnim pohledu na spravu aukce. Ten musi byt bezpodminecne rychly.

> A zajímá tě to až po skončení aukce nebo i v průběhu?

Staci po skonceni.

**Comment by foton** [comment]
Associace `auction.winner` nastavovaná po `auction.close_bidding` :
```
Auctify::Sale::Auction.includes(:winner).collect(&:winner)

=> SELECT "auctify_sales".* FROM "auctify_sales" WHERE "auctify_sales"."type" =  "Auctify::Sale::Auction"
=> SELECT "users".* FROM "users" WHERE "users"."id" IN (585460615, 903912321)
```

**Comment by foton** [comment]
`auction.bids_count` bere v potaz jen nezrušené příhozy.
