### ISSUE TITLE
Zdvojena validace prihozu

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#13]
Výše příhozu je nižší než aktuální cena
Výše příhozu je nižší než aktuální minimální příhoz

Minimalni prihoz vzdy bude vetsi nez aktualni cena, ne? Rad bych vypisoval validacni hlasky pri neuspesnem prihozu v karte bez nejakeho filtrovani.

**Comment by foton** [comment]
closed in 5ebf73d..db6c18d
