### ISSUE TITLE
Nejde zvysit vlastni prihoz

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#14]
scenar, test si prosim udelej sam ;) 

1. predmet bez bidu
2. muj bid `{ price: 5000 }` - ok - ulozi se a upravi se `current_minimal_bid`
3. muj bid `{ price: 10000 }` - api ok - nic se ale neulozi a nezmeni se `current_minimal_bid`
4. cizi bid `{ price: 10000 }` - ok  - ulozi se a upravi se `current_minimal_bid`
5. muj bid `{ price: 20000 }` - ok  - ulozi se a upravi se `current_minimal_bid`
6. muj bid `{ price: 30000 }` - api ok - nic se ale neulozi a nezmeni se `current_minimal_bid`

**Comment by foton** [comment]
No to ani nemá jít. Myslím, že jsem to vyčetl ze specifikace / ACB nebo mi to někdo řekl. Dražitel nemůže přehazovat sám sebe.

**Comment by foton** [comment]
@mreq ^

**Comment by mreq** [comment]
Pak tam prosim pridej validaci a chybu. Takhle API vraci ok, jako kdyby bylo vse v poradku.

**Comment by foton** [comment]
Chyby jsou v `new_bid.errors` nebo vráceném JSONu.
https://github.com/sinfin/auctify/blob/master/test/controllers/auctify/api/v1/auctions_controller_test.rb#L117
