### ISSUE TITLE
Drazit smi jen nekteri uzivatele

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#16]
V aukciaukci jde konkretne o uzivatele v AASM stavu `approved`. Pridame pro bidder asi nejakou metodu? Asi netreba resit cely cancancan...

**Comment by foton** [comment]
Nerozumím požadavku. 
Máš na mysli, že je potřeba prověřit jestli samotný bidder má pravo přihazovat? 
Jestli jo, tak by neměl mít vůbec `bidder_registration`. 
Nebo má jít o dynamickou záležitost? Že je mu to zakázáno i během aukce?

**Comment by mreq** [comment]
Ano, jestli se to vyresi nepovolenim prihazovani, nebo neexistenci bidder_registration je jedno. S bidder_registration se v AA nepocitalo, tak proto je to mozna matouci.

V AA maji uzvatele AASM. Pokud nemaji AASM stav `approved`, tak maji omezene moznosti. Mimo jine nemuzou prihazovat.
