### ISSUE TITLE
Zvlastni poradi bidu pri max_price

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#22]
Razeno dle id. Ocekaval bych, ze max_price preplacnuti bude poslednim bidem. Poslednim bidem (nejvyssi id) je ale bid pokousejici se prehodit aktualni cenu (nizsim bidem, nez limit).

![image](https://user-images.githubusercontent.com/1286942/117415236-6005c980-af18-11eb-86a6-3f7b441a39ac.png)

**Comment by foton** [comment]
Na `id`  bych se nespoléhal. Proto má `Auctify::Bid` `scope :ordered, -> { order(price: :desc, created_at: :asc, id: :asc) }`.
Podívám se proč je to otočené (v principu by nemělo)

**Comment by foton** [comment]
Dokonce jsem si to napsal do komentářů :
```
def append_bids!
        # saving first, so it will still be winning even if both have same price
        if @updated_win_bid.present?
          fail! unless @updated_win_bid.save
        end

        fail! unless bid.save
      end

```

**Comment by foton** [comment]
je to kvůli tomu když jeden dá `max_price: 1000` (a cena poskočí na např 800) a druhý pak dá `price: 1000`. Cena se vyšroubuje na 1000, ale vyhrávat má ten první příhoz.

**Comment by mreq** [comment]
Ok, takze vyresim zmenou `order(id: :desc)` na `ordered`?
