### ISSUE TITLE
Pridat applied_bid_count pro aukce

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#23]
Necham na tobe, jestli vedle bid_count, nebo jestli jen bid_count prejmenovat. Takhle je to ale bez pohledu do strev auctify nejasne, jaky pocet to vlastne udava.

Pak prosim updatni v AA a nahrad vsechna `bid_count` volani tim `applied_bid_count`.

**Comment by foton** [comment]
Opraveno i v AA
