### ISSUE TITLE
Zvazit sql index pro bids cancelled

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#26]
Vyuziva se v kazdem selectu skrze applied_bids. Nevim ale, jestli je to realne prinosne, kdyz vetsina tabulky bude mit false.

**Comment by foton** [comment]
Zajímavé je, že jsem ho tam chtěl už při vytvoření https://github.com/sinfin/auctify/blob/master/db/migrate/20210503095704_add_cancelled_to_auctify_bids.rb

A taky mi, asi, zbrzdil testy ( 5 sec -> 5.4 sec). Ale to je neprůkazné.

Closed in 1a2a76bbed87b938f76448db1575d8f07105ffef
