### ISSUE TITLE
Polepsit validaci max_price pro prihozy

### ISSUE THREAD

**Issue by mreq** [sinfin/auctify#33]
Kdyz odeslu formular s `bid[max_price]`, ktery je prilis nizky, tak se mi vratit bid, kde je nevalidni `price` a ne `max_price`. Ve formulari to pak muze byt matouci.

https://user-images.githubusercontent.com/1286942/122718172-e712c500-d26c-11eb-8553-c6e5865a9324.mp4

**Comment by foton** [comment]
> .... s `bid[max_price]`....., tak se mi vratit bid, kde je nevalidni `price` a ne `max_price`. ....

Předpokládám, že význam má být 
- dávám limit => "váš limit je menší než min příhoz"
- dávám přímý příhoz  => " váš příhoz je menší než min příhoz"

@pochopil jsem to správně?
