### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by dcalixto** [sinfin/auctify#65]
Hello, i'm still confuse on implement this gem!

has any tutorial or exemple?
because for exemple:
after post creation how to bid the post and how to list the auctions?

  ```
def create

    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
```

**Comment by foton** [comment]
Hi @dcalixto 
where did You find anything about `post` model? 
There is `Auctify::Sale::Auction` class, and you can call `auction.bid!(bid)` . 
See `tests`, eg. [bidding_test](https://github.com/sinfin/auctify/blob/0ffcbcff8e9997284d274e5e6903a5613c902b0d/test/models/auctify/sale/auction_bidding_test.rb) could be helpfull.

**Comment by dcalixto** [comment]
> Hi @dcalixto where did You find anything about `post` model? There is `Auctify::Sale::Auction` class, and you can call `auction.bid!(bid)` . See `tests`, eg. [bidding_test](https://github.com/sinfin/auctify/blob/0ffcbcff8e9997284d274e5e6903a5613c902b0d/test/models/auctify/sale/auction_bidding_test.rb) could be helpfull.


I thought that auction integrate any model, so is it direct?

**Comment by dcalixto** [comment]
forget it too complicated to implement this
